version: '3'
services:
  web:
    image: node:18
    user: node
    command: sh -c "npm install && npx prisma migrate deploy && node --inspect=0.0.0.0:9229 node_modules/next/dist/bin/next dev"
    depends_on:
      - db
    environment:
      - USE_POSTGRES_CACHE=true
      - DATABASE_URL=postgres://postgres:secret@db/postgres
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
