version: '3'
services:
  web:
    image: node:16
    user: node
    command: sh -c "npm install && npx prisma migrate && npx prisma migrate deploy && npm run dev"
    depends_on:
      - db
    environment:
      - USE_POSTGRES_CACHE=true
      - DATABASE_URL=postgres://postgres:secret@db/postgres
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
